apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
<<<<<<< HEAD
          image: mudraboyinagayathri29/wisecow:latest
=======
          image: image: mudraboyinagayathri29/wisecow:latest
>>>>>>> b2ab8b75ac48353bfb6d8128317ad0c6b4db2643
          imagePullPolicy: Always
          ports:
            - containerPort: 4499
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
